baseURL = 'https://hazarre.github.io/'
languageCode = 'en-us'
title = "HenryChang"

# -- Markup --
# These settings are required for the theme to function.

[params]
  author = 'Li-Heng Henry Chang 張立恆'
  custom_css = ["css/syntax.css","css/style.css", "css/tufte.css"]
  custom_js = ["js/script.js"]
  email = "lihengc6@gmail.com" 

  #social links#
  [[params.social]]
    icon_name = "fa-linkedin"
    url = "https://www.linkedin.com/in/lihengchang/"
  [[params.social]]
    icon_name = "fa-github"
    url = "https://github.com/Hazarre"
  [[params.social]]
    icon_name = "#fa-instagram"
    url = "https://github.com/Hazarre"
  [[params.social]]
    icon_name = "#fa-medium"
    url = "https://github.com/Hazarre"
  [[params.social]]
    icon_name = "#fa-twitter"
    url = "https://github.com/Hazarre"

  #other links#
  [[params.otherSocial]]
    icon_name = "fa-goodreads"
    url = "https://www.goodreads.com/user/show/141376873-henry-chang"
  
  [[params.otherSocialLinks]]
    text = "Shadertoy"
    url = "https://www.shadertoy.com/user/lihengc6"


[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    pre = "pen-tool"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 3

[markup]
  [markup.highlight]
    noClasses = false
    anchorLineNos = false
    codeFences = true
    hl_Lines = ''
    lineAnchors = '1'
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noHl = false
    style = 'monokai'
    tabWidth = 4

